export const researchFeatures = [
  {
    id: "quantum-black-holes",
    title: "Quantum black holes & horizon physics",
    description: "I study how quantum gravity may alter black-hole horizons, interiors, entropy, and singularities, with the aim of turning microscopic models into observable signatures.",
    image: "/media/2015/12/uhrn1prime.png",
    alt: "Causal diagram from archived research on black holes and gravity",
    caption: "A causal-structure diagram from the black-hole research archive.",
    archiveHref: "/welcome/research/black-hole-physics/",
    papers: [
      { year: "2025", title: "Self-regularized entropy: How much do quantum black holes violate the no-hair theorem?", href: "https://arxiv.org/abs/2508.20421" },
      { year: "2024", title: "The complete initial-boundary-value problem for modelling black-hole echoes", href: "https://arxiv.org/abs/2409.17970" },
      { year: "2022", title: "Scale-invariance at the core of quantum black holes", href: "https://arxiv.org/abs/2203.02559" },
    ],
  },
  {
    id: "gravitational-waves",
    title: "Gravitational-wave astronomy & black-hole spectroscopy",
    description: "I develop waveform, time-frequency, and Bayesian methods for testing strong gravity with present and future observatories, including ringdown spectroscopy, stochastic backgrounds, LISA sources, and post-merger echoes.",
    image: "/media/2017/01/mergingblackholes_v2-1.jpg",
    alt: "Illustration of merging black holes and emitted gravitational waves",
    caption: "A compact-binary merger provides a laboratory for strong gravity.",
    archiveHref: "/welcome/research/black-hole-physics/",
    papers: [
      { year: "2025", title: "Black hole spectroscopy: from theory to experiment", href: "https://arxiv.org/abs/2505.23895" },
      { year: "2025", title: "Waveform modelling for the Laser Interferometer Space Antenna", href: "https://arxiv.org/abs/2311.01300" },
      { year: "2024", title: "Spectrogram correlated stacking of the stochastic gravitational-wave background", href: "https://arxiv.org/abs/2305.03090" },
      { year: "2023", title: "Model-independent search for quasinormal modes of gravitational-wave echoes", href: "https://arxiv.org/abs/2308.01017" },
    ],
  },
  {
    id: "early-universe",
    title: "The Big Bang, early universe & quantum cosmology",
    description: "I explore how ultraviolet-complete, holographic, and quantum descriptions of gravity can explain cosmic initial conditions, tested against inflationary predictions and precision cosmology.",
    image: "/media/2017/01/hc_cartoon-001.jpeg",
    alt: "Illustration connecting the early universe to the cosmic microwave background and present-day galaxies",
    caption: "A visual summary of how primordial physics is tested with the cosmic sky.",
    archiveHref: "/welcome/research/early-universe-cosmology/",
    papers: [
      { year: "2025", title: "Ultraviolet completion of the Big Bang in quadratic gravity", href: "https://arxiv.org/abs/2510.18733" },
      { year: "2017", title: "Constraining holographic cosmology using Planck data", href: "https://arxiv.org/abs/1703.05385" },
      { year: "2016", title: "From Planck data to Planck era: observational tests of holographic cosmology", href: "https://arxiv.org/abs/1607.04878" },
    ],
  },
  {
    id: "dark-energy-modified-gravity",
    title: "Dark energy & modified gravity",
    description: "I investigate whether cosmic acceleration and current cosmological tensions reveal departures from general relativity, including cuscuton-like theories, horizon-scale Lorentz violation, and scale-dependent gravity.",
    image: "/media/2015/12/comcm.png",
    alt: "Scientific plot comparing models across dark-matter halo mass",
    caption: "An archived model comparison illustrating scale-dependent cosmic physics.",
    archiveHref: "/welcome/research/modified-gravity-and-the-cosmological-constant-problem/",
    papers: [
      { year: "2024", title: "A cosmic glitch in gravity", href: "https://arxiv.org/abs/2311.03028" },
      { year: "2024", title: "A glitch in gravity: cosmic Lorentz violation from fiery Big Bang to glacial heat death", href: "https://arxiv.org/abs/2412.09568" },
      { year: "2023", title: "Effective Cuscuton Theory", href: "https://arxiv.org/abs/2312.06066" },
    ],
  },
  {
    id: "dark-matter-structure",
    title: "Dark matter, galaxies & nonlinear structure",
    description: "I use cosmological simulations, analytic models, and interpretable machine learning to map dark objects and understand nonlinear structure, from dark-galaxy prediction to halo outskirts and phase space.",
    image: "/media/2016/01/p2sad_subs_only-eps-converted-to.jpg",
    alt: "Scientific phase-space plot for dark-matter halos of different masses",
    caption: "Phase-space structure across dark-matter haloes of different masses.",
    archiveHref: "/welcome/research/understanding-dark-matter-and-dark-energy/",
    papers: [
      { year: "2025", title: "Where are all the dark galaxies?", href: "https://arxiv.org/abs/2507.01814" },
      { year: "2022", title: "On the outskirts of dark matter haloes", href: "https://arxiv.org/abs/2210.11499" },
      { year: "2019", title: "Amending the halo model to satisfy cosmological conservation laws", href: "https://arxiv.org/abs/1912.04872" },
      { year: "2015", title: "Universal clustering of dark matter in phase space", href: "https://arxiv.org/abs/1508.02713" },
    ],
  },
  {
    id: "cosmic-gas-cmb",
    title: "Cosmic gas, the CMB & missing baryons",
    description: "I use the thermal and kinematic Sunyaev–Zel’dovich effects to trace hot electrons, galaxy motions, and the baryonic content of halos and intergalactic space while separating radio, dust, and infrared foregrounds.",
    image: "/media/2015/07/planck_cmb.jpg",
    alt: "All-sky map of fluctuations in the cosmic microwave background",
    caption: "The cosmic microwave background is both a primordial record and a backlight for cosmic gas.",
    archiveHref: "/welcome/research/missing-baryons-of-the-universe/",
    papers: [
      { year: "2026", title: "Thermal Sunyaev–Zel’dovich cross-correlations with unWISE galaxies", href: "https://arxiv.org/abs/2606.28099" },
      { year: "2013", title: "An optimal and model-independent measurement of the intracluster pressure profile", href: "https://arxiv.org/abs/1304.6457" },
      { year: "2012", title: "First measurement of the bulk flow of nearby galaxies using the CMB", href: "https://arxiv.org/abs/1207.1721" },
    ],
  },
  {
    id: "compact-objects",
    title: "Compact objects, accretion disks & electromagnetic probes",
    description: "I study observable signatures of black holes, neutron stars, white dwarfs, and modified strong gravity. Accretion spectra, self-lensing, and eclipses complement gravitational-wave tests.",
    image: "/media/2018/03/mass_spin.jpg",
    alt: "Scientific plot comparing inferred black-hole mass and spin",
    caption: "Mass and spin constraints illustrate the link between compact-object models and data.",
    archiveHref: "/welcome/research/understanding-accretion-disks/",
    papers: [
      { year: "2025", title: "Accretion disk dynamics in Teleparallel Born–Infeld gravity", href: "https://arxiv.org/abs/2502.03775" },
      { year: "2024", title: "Self-lensing and eclipsing signals from detached compact objects in TESS", href: "https://arxiv.org/abs/2409.12441" },
    ],
  },
  {
    id: "quantum-spacetime-foundations",
    title: "Quantum spacetime, analogue gravity & foundations",
    description: "I investigate operational and analogue probes of quantum spacetime, from detectors in superposed geometries to condensed-matter systems that reproduce black-hole thermodynamics, alongside surveys of unresolved foundational questions.",
    image: "/media/2025/05/image.png",
    alt: "Artist's impression of the energetic early universe",
    caption: "Foundational questions connect quantum spacetime, cosmology, and observable tests.",
    archiveHref: "/welcome/research/quantum-field-theory-in-curved-spacetime/",
    papers: [
      { year: "2024", title: "Accelerated detector in a superposed spacetime", href: "https://arxiv.org/abs/2409.06818" },
      { year: "2024", title: "Smart Holes: analogue black holes with the right temperature and entropy", href: "https://arxiv.org/abs/2412.08517" },
      { year: "2026", title: "Big Mysteries Survey", href: "https://arxiv.org/abs/2605.11058" },
      { year: "2025", title: "Copenhagen Survey on Black Holes and Fundamental Physics", href: "https://arxiv.org/abs/2503.15776" },
    ],
  },
];

export type GroupMember = {
  name: string;
  role: string;
  years: string;
  research: string;
  destination: string;
  image?: string;
  profileHref?: string;
  verification?: string;
};

export const currentPeople: GroupMember[] = [
  {
    name: "Alice Chen",
    role: "PhD researcher",
    years: "2023–present",
    research: "Machine learning and cosmic structure formation, following earlier MSc work on cosmological structure.",
    destination: "University of Waterloo and Perimeter Institute.",
    profileHref: "https://uwaterloo.ca/astrophysics-centre/contacts/alice-chen",
    verification: "Please confirm current status after 2026 and provide a preferred portrait.",
  },
  {
    name: "Ruolin Liu",
    role: "PhD researcher",
    years: "Current",
    research: "Quadratic gravity, the Big Bang, quantum black holes, and quantum sensors.",
    destination: "University of Waterloo and Perimeter Institute.",
    profileHref: "https://uwaterloo.ca/astrophysics-centre/contacts/ruolin-liu",
    verification: "Please provide a preferred portrait.",
  },
  {
    name: "Hassan Subhi",
    role: "MMath researcher",
    years: "2025–2027",
    research: "Gravitational-wave echoes in pulsar-timing data; co-supervised with Florian Girelli.",
    destination: "University of Waterloo.",
    profileHref: "https://uwaterloo.ca/i-comp-data/funded-projects",
    verification: "Please provide a preferred portrait.",
  },
  {
    name: "Shokoufe Faraji",
    role: "Postdoctoral researcher",
    years: "2024–2026",
    research: "Strong gravity, quantum gravity, and accretion around black holes.",
    destination: "Perimeter Institute and University of Waterloo.",
    profileHref: "https://perimeterinstitute.ca/people/shokoufe-faraji",
    verification: "Please confirm whether the appointment continued after March 2026 and provide a preferred portrait.",
  },
];

export const alumniPeople: GroupMember[] = [
  {
    name: "Conner Dailey",
    role: "PhD researcher",
    years: "2020–2025",
    research: "The initial-boundary-value problem in numerical relativity and the modelling of black-hole echoes.",
    destination: "Postdoctoral researcher, Friedrich Schiller University Jena.",
    image: "/media/2024/09/conner-dailey-web.jpg",
    profileHref: "https://taketwicedailey.com/",
  },
  {
    name: "Matthew Robbins",
    role: "PhD researcher",
    years: "2017–2021",
    research: "Gravitational waves, Bose–Einstein-condensate detectors, modified gravity, and black holes.",
    destination: "Assistant Professor, Teaching Stream, University of Toronto.",
    image: "/media/2018/07/image-2.jpg",
    profileHref: "https://www.physics.utoronto.ca/members/robbins-matthew/",
  },
  {
    name: "José Tomás Gálvez Ghersi",
    role: "Visiting PhD researcher",
    years: "2017–2018",
    research: "Local-observer temperature in curved spacetime and modified gravity.",
    destination: "Associate Professor, Universidad de Ingeniería y Tecnología, Peru.",
    image: "/media/2018/04/jose-tomasgalvez-ghersi040520101032_15.jpg",
    profileHref: "https://cris.utec.edu.pe/es/persons/jos%C3%A9-tom%C3%A1s-g%C3%A1lvez-ghersi/",
  },
  {
    name: "Mohammad Hossein Zhoolideh Haghighi",
    role: "Visiting PhD researcher",
    years: "2016–2017",
    research: "X-ray cooling flows, turbulent heating, and modified gravity.",
    destination: "Active researcher affiliated with K. N. Toosi University and IPM.",
    image: "/media/2018/07/picture-9480-1488993131.jpg",
    profileHref: "https://link.springer.com/article/10.1140/epjc/s10052-026-15345-4",
    verification: "Please confirm current title and primary institution.",
  },
  {
    name: "Chanda Prescod-Weinstein",
    role: "Co-supervised PhD researcher",
    years: "2008–2010",
    research: "Cosmic acceleration, quantum gravity, and early-universe cosmology.",
    destination: "Associate Professor, University of New Hampshire.",
    image: "/media/2015/07/chandacake_resized1-e1439880392164.jpg",
    profileHref: "https://cola.unh.edu/person/chanda-prescod-weinstein",
  },
  {
    name: "Daniel Guariento",
    role: "Postdoctoral researcher",
    years: "2013–2017",
    research: "Cosmological black holes, self-gravitating fields, and cosmic censorship.",
    destination: "Professor, Conestoga College.",
    image: "/media/2015/07/s200_daniel-guariento.jpg",
    profileHref: "https://www.researchgate.net/profile/Daniel-Guariento",
  },
  {
    name: "Michael Meiers",
    role: "Master’s researcher",
    years: "2014–2016",
    research: "Universal horizons and Lorentz-violating black holes.",
    destination: "Walmart Global Tech.",
    image: "/media/2015/07/michael-meiers-e1440388294268.jpg",
    profileHref: "https://www.linkedin.com/in/michael-meiers",
  },
  {
    name: "Samantha Hergott",
    role: "Master’s researcher",
    years: "2018–2020",
    research: "Thermal links between the Big Bang and black holes.",
    destination: "Recent York University and Perimeter Institute PhD graduate and black-hole researcher.",
    image: "/media/2019/05/unnamed-1.jpg",
    profileHref: "https://orcid.org/0000-0002-3954-3235",
    verification: "Please confirm current appointment.",
  },
  {
    name: "Aditya Dhumuntarao",
    role: "Visiting PhD researcher",
    years: "2017–2018",
    research: "Local temperature and quantum field theory in curved spacetime.",
    destination: "Postdoctoral Appointee, Sandia National Laboratories.",
    image: "/media/2018/04/aditya-e1522979303913.jpg",
    profileHref: "https://www.sandia.gov/people/staff/aditya-dhumuntarao/",
  },
  {
    name: "Naritaka Oshita",
    role: "Visiting PhD and postdoctoral researcher",
    years: "2018–2021",
    research: "Black-hole echoes and quantum black-hole seismology.",
    destination: "Lecturer, Kindai University; visiting researcher, RIKEN.",
    image: "/media/2019/05/picture-41146-1550674152.jpg",
    profileHref: "https://research.kindai.ac.jp/search/detail.html?lang=en&st=researcher&systemId=7142158ed6512951",
  },
  {
    name: "Mehdi Saravani",
    role: "PhD researcher",
    years: "2011–2016",
    research: "Nonlocality, causal sets, quantum field theory, and black holes.",
    destination: "Goldman Sachs, United Kingdom.",
    image: "/media/2015/07/11083918_10205089110560914_8792186586980474424_o-e1439884225953.jpg",
    profileHref: "https://uk.linkedin.com/in/mehdi-saravani",
    verification: "Please confirm current title.",
  },
  {
    name: "Hannah Dykaar",
    role: "Undergraduate researcher",
    years: "2016",
    research: "Gravitational-wave echoes from the abyss.",
    destination: "Postdoctoral Fellow, McGill University.",
    image: "/media/2015/07/unnamed-e1502618910753.jpg",
    profileHref: "https://www.dhaggard.physics.mcgill.ca/research-group",
  },
  {
    name: "Tianyi Yang",
    role: "Master’s researcher",
    years: "2018–2020",
    research: "Cosmic filaments, Gaia kinematics, and thermal Sunyaev–Zel’dovich gas.",
    destination: "Postdoctoral researcher, Liverpool John Moores University.",
    image: "/media/2018/04/photo-1-e1522977249934.png",
    profileHref: "https://uwaterloo.ca/scholar/mjhudson/group-members",
  },
  {
    name: "Mansour Karami",
    role: "PhD researcher",
    years: "2014–2018",
    research: "Dark matter, microlensing, halo modelling, and Event Horizon Telescope methods.",
    destination: "AI engineering, HOOPP.",
    image: "/media/2015/07/mypic-e1440388587637.jpg",
    profileHref: "https://ca.linkedin.com/in/mansour-karami",
    verification: "Please confirm current title.",
  },
  {
    name: "Razieh Pourhasan",
    role: "PhD researcher",
    years: "2011–2014",
    research: "Holography, the Big Bang, and spacetime entanglement.",
    destination: "Data Scientist, Government of Canada.",
    image: "/media/2015/07/msc-razieh-pourhasan-0001-20140805-158x185-e1439883375483.jpg",
    profileHref: "https://www.robbmanngroup.ca/people",
  },
  {
    name: "Chiamaka Okoli",
    role: "Master’s and PhD researcher",
    years: "2012–2018",
    research: "Dark matter, halo concentration, and cosmological neutrino wakes.",
    destination: "In memoriam (died June 2019).",
    image: "/media/2015/07/26d8193-e1440385821548.jpg",
    profileHref: "https://perimeterinstitute.ca/news/perimeter-mourns-passing-chiamaka-okoli-brilliant-rising-star-cosmology",
  },
  {
    name: "Jesús Zavala",
    role: "Postdoctoral researcher",
    years: "2010–2013",
    research: "Dark-matter phase space, structure, and galaxy formation.",
    destination: "Professor, University of Iceland.",
    image: "/media/2015/07/jesus.jpg",
    profileHref: "https://hi.is/staff/jzavala",
  },
  {
    name: "Elizabeth “Beth” Gould",
    role: "PhD researcher",
    years: "2011–2017",
    research: "Early-universe cosmology, quantum foundations, and holographic cosmology.",
    destination: "Last verified at Queen’s University and the McDonald Institute.",
    image: "/media/2015/07/elizabethgould140920101004_25-e1440386323567.jpg",
    verification: "Please confirm current destination.",
  },
  {
    name: "Yasaman K. Yazdi",
    role: "Master’s and PhD researcher",
    years: "2011–2017",
    research: "Vacuum states, entropy, black holes, and causal sets.",
    destination: "Postdoctoral Fellow, Dublin Institute for Advanced Studies.",
    image: "/media/2015/07/img_1650_2-e1440387894698.jpg",
    profileHref: "https://royalsociety.org/science-events-and-lectures/2026/09/path-to-quantum-gravity/",
  },
  {
    name: "Morag Scrimgeour",
    role: "Postdoctoral researcher",
    years: "2013–2014",
    research: "Large-scale structure and cosmological neutrinos.",
    destination: "Scientist, Canon Medical Research Europe.",
    image: "/media/2015/07/morag-e1439882456847.jpg",
    profileHref: "https://uwaterloo.ca/scholar/mjhudson/group-members",
  },
  {
    name: "Guilhem Lavaux",
    role: "CITA National Fellow",
    years: "2011–2013",
    research: "Missing baryons, cosmic flows, and large-scale structure.",
    destination: "CNRS Research Director, Institut d’Astrophysique de Paris.",
    image: "/media/2015/07/me-e1439881349111.jpg",
    profileHref: "https://www.guilhem-lavaux.eu/cv.php",
  },
  {
    name: "Zachary Elgood",
    role: "Undergraduate researcher",
    years: "2016",
    research: "Einstein–Aether black holes.",
    destination: "Most recent public record: independent researcher.",
    image: "/media/2018/04/23736341_10208680484004424_6004154379800524268_o-e1522976735527.jpg",
    verification: "Please confirm current destination.",
  },
  {
    name: "Connor Adair",
    role: "Undergraduate researcher",
    years: "2017",
    research: "Gravitational-wave echoes.",
    destination: "Candu Energy Inc.",
    image: "/media/2019/02/profile-pic.jpg",
    profileHref: "https://ca.linkedin.com/in/connor-adair-614b24177",
  },
  {
    name: "Natacha Altamirano",
    role: "PhD researcher",
    years: "2014–2018",
    research: "Quantum gravity, black holes, and holographic cosmology.",
    destination: "Senior Director, Data Science, Birch Hill Equity Partners.",
    image: "/media/2018/07/img_3950-e1531213584786.jpg",
    profileHref: "https://perimeterinstitute.ca/training/alumni-network/perimeter-circle-alumni-stories/natacha-altamirano-bringing-data-driven",
  },
  {
    name: "Nosiphiwo Zwane",
    role: "PhD researcher",
    years: "2013–2017",
    research: "Causal-set phenomenology, dark energy, and Everpresent Lambda.",
    destination: "Lecturer and researcher, University of Eswatini.",
    image: "/media/2015/07/aims_nosiphiwo_zwane-e1440389254459.jpg",
    verification: "Please confirm current title.",
  },
  {
    name: "Shant Baghram",
    role: "Postdoctoral researcher",
    years: "2011–2012",
    research: "Dark-matter halo substructure, pulsar timing, and modified gravity.",
    destination: "Professor, Sharif University of Technology.",
    image: "/media/2015/07/photo.jpg",
    profileHref: "https://www.iau.org/IAU/Shared_Content/Contacts/ContactLayouts/Profile.aspx?ID=38854",
  },
  {
    name: "Farbod Kamiab",
    role: "PhD researcher",
    years: "2011–2015",
    research: "Neutron stars, modified gravity, and numerical relativity.",
    destination: "Director of AI and Data Engineering, Everlywell.",
    image: "/media/2015/07/shapeimage_6-e1439883765262.png",
    profileHref: "https://www.linkedin.com/in/farbod-kamiab-78461135",
  },
  {
    name: "Jahed Abedi",
    role: "Visiting and co-supervised PhD researcher",
    years: "2016–2018",
    research: "Black-hole echoes and gravitational-wave data.",
    destination: "Assistant Professor, Beijing Institute of Mathematical Sciences and Applications.",
    image: "/media/2015/07/photo1.jpg",
    profileHref: "https://www.bimsa.cn/detail/JahedAbedi.html",
  },
  {
    name: "Siavash Aslanbeigi",
    role: "PhD researcher",
    years: "2010–2014",
    research: "Causal sets, nonlocality, and cosmological structure.",
    destination: "BMO Capital Markets.",
    image: "/media/2015/07/29cfc18.jpg",
    profileHref: "https://ca.linkedin.com/in/siavash-aslanbeigi-b8232745",
    verification: "Please confirm current title.",
  },
  {
    name: "Krishan Saraswat",
    role: "PhD researcher",
    years: "2018–2023",
    research: "Black-hole microstates, echoes, quantum chaos, and holography.",
    destination: "Postdoctoral Researcher, University of California, Santa Barbara.",
    image: "/media/2019/02/0.jpeg",
    profileHref: "https://orcid.org/0000-0002-0350-7822",
  },
  {
    name: "Morgan Lynch",
    role: "Visiting PhD researcher",
    years: "2015–2016",
    research: "Curved-spacetime quantum field theory and the Unruh effect.",
    destination: "Postdoctoral researcher, Max Planck Institute for Nuclear Physics.",
    image: "/media/2015/07/lynch_300-e1440391901651.jpg",
  },
  {
    name: "Jolene Zheng",
    role: "Undergraduate researcher",
    years: "2021",
    research: "COVID forecasting and dashboard development.",
    destination: "Most recent group record: Software Engineer, Bloomberg.",
    image: "/media/2021/04/image-14.png",
    profileHref: "https://jolenezheng.github.io/",
    verification: "Please confirm current employer.",
  },
];

export const currentMembers = currentPeople.map((member) => member.name);

export const recentTalks = [
  {
    date: "April 2025",
    title: "Copenhagen Survey on Black Holes and Fundamental Physics",
    venue: "IPM Physics Colloquium, Iran (in Farsi)",
  },
  {
    date: "March 2025",
    title: "Battle of the Big Bang: How the Universe Began (and Why It’s a Big Mystery!)",
    venue: "Physics Literacy for Kids",
  },
  {
    date: "July 2024",
    title: "Quantum Spacetime in the Sky: From Horizon to Horizon",
    venue: "ICBS 2024, BIMSA, China",
  },
  {
    date: "November 2023",
    title: "Quantum Spacetime & the Cosmic Endgame",
    venue: "Simon Fraser University Physics Colloquium",
  },
];

export const talksArchiveUrl = "https://www.dropbox.com/scl/fo/h3czitrga1jxz2tiev3dz/AA4bmJHNu_nipZS4aF5guus?rlkey=hr3wsei04cwpvprfe0952auim&dl=0";

export const recentUpdates = [
  {
    date: "March 2025",
    title: "Join Me at the Royal Institution — Battle of the Big Bang",
    href: "/2025/03/25/join-me-at-the-royal-institution-on-june-28-battle-of-the-big-bang/",
  },
  {
    date: "January 2025",
    title: "Meaning of Beauty :معنی قشنگ",
    href: "/2025/01/20/meaning-of-beauty-%d9%85%d8%b9%d9%86%db%8c-%d9%82%d8%b4%d9%86%da%af/",
  },
  {
    date: "October 2024",
    title: "Battle of the Big Bang: New Tales of Our Cosmic Origins",
    href: "/2024/10/19/battle-of-the-big-bang-new-tales-of-our-cosmic-origins/",
  },
];

export const externalProfiles = [
  { label: "arXiv", href: "https://arxiv.org/search/?searchtype=author&query=Afshordi%2C+N&order=-announced_date_first&size=200&abstracts=show" },
  { label: "INSPIRE", href: "https://inspirehep.net/authors/1023532" },
  { label: "NASA ADS", href: "https://ui.adsabs.harvard.edu/search/q=author%3A%22Afshordi%22" },
  { label: "Google Scholar", href: "https://scholar.google.ca/citations?user=xWZGFlEAAAAJ&hl=en" },
  { label: "ORCID", href: "https://orcid.org/0000-0002-9940-7040" },
];

export const socialProfiles = [
  { label: "LinkedIn", href: "https://www.linkedin.com/in/niayesh-afshordi-61739462/" },
  { label: "X", href: "https://x.com/nafshordi" },
  { label: "Bluesky", href: "https://bsky.app/profile/nafshordi.bsky.social" },
  { label: "Facebook", href: "https://www.facebook.com/niayesh.afshordi" },
  { label: "Threads", href: "https://www.threads.net/@nafshordi" },
  { label: "Instagram", href: "https://www.instagram.com/nafshordi/" },
] as const;
