export const researchFeatures = [
  {
    id: "quantum-black-holes",
    title: "Quantum black holes & horizon physics",
    description: "I study how quantum gravity may alter black-hole horizons, interiors, entropy, and singularities, with the aim of turning microscopic models into observable signatures.",
    image: "/media/2015/12/uhrn1prime.png",
    alt: "Causal diagram from archived research on black holes and gravity",
    caption: "A causal-structure diagram from the black-hole research archive.",
    archiveHref: "/welcome/research/black-hole-physics/",
    papers: [
      { year: "2025", title: "Self-regularized entropy: How much do quantum black holes violate the no-hair theorem?", href: "https://arxiv.org/abs/2508.20421" },
      { year: "2024", title: "The complete initial-boundary-value problem for modelling black-hole echoes", href: "https://arxiv.org/abs/2409.17970" },
      { year: "2022", title: "Scale-invariance at the core of quantum black holes", href: "https://arxiv.org/abs/2203.02559" },
    ],
  },
  {
    id: "gravitational-waves",
    title: "Gravitational-wave astronomy & black-hole spectroscopy",
    description: "I develop waveform, time-frequency, and Bayesian methods for testing strong gravity with present and future observatories, including ringdown spectroscopy, stochastic backgrounds, LISA sources, and post-merger echoes.",
    image: "/media/2017/01/mergingblackholes_v2-1.jpg",
    alt: "Illustration of merging black holes and emitted gravitational waves",
    caption: "A compact-binary merger provides a laboratory for strong gravity.",
    archiveHref: "/welcome/research/black-hole-physics/",
    papers: [
      { year: "2025", title: "Black hole spectroscopy: from theory to experiment", href: "https://arxiv.org/abs/2505.23895" },
      { year: "2025", title: "Waveform modelling for the Laser Interferometer Space Antenna", href: "https://arxiv.org/abs/2311.01300" },
      { year: "2024", title: "Spectrogram correlated stacking of the stochastic gravitational-wave background", href: "https://arxiv.org/abs/2305.03090" },
      { year: "2023", title: "Model-independent search for quasinormal modes of gravitational-wave echoes", href: "https://arxiv.org/abs/2308.01017" },
    ],
  },
  {
    id: "early-universe",
    title: "The Big Bang, early universe & quantum cosmology",
    description: "I explore how ultraviolet-complete, holographic, and quantum descriptions of gravity can explain cosmic initial conditions, tested against inflationary predictions and precision cosmology.",
    image: "/media/2017/01/hc_cartoon-001.jpeg",
    alt: "Illustration connecting the early universe to the cosmic microwave background and present-day galaxies",
    caption: "A visual summary of how primordial physics is tested with the cosmic sky.",
    archiveHref: "/welcome/research/early-universe-cosmology/",
    papers: [
      { year: "2025", title: "Ultraviolet completion of the Big Bang in quadratic gravity", href: "https://arxiv.org/abs/2510.18733" },
      { year: "2017", title: "Constraining holographic cosmology using Planck data", href: "https://arxiv.org/abs/1703.05385" },
      { year: "2016", title: "From Planck data to Planck era: observational tests of holographic cosmology", href: "https://arxiv.org/abs/1607.04878" },
    ],
  },
  {
    id: "dark-energy-modified-gravity",
    title: "Dark energy & modified gravity",
    description: "I investigate whether cosmic acceleration and current cosmological tensions reveal departures from general relativity, including cuscuton-like theories, horizon-scale Lorentz violation, and scale-dependent gravity.",
    image: "/images/effective-cuscuton-geometry.png",
    alt: "Stack of spatial branes in the geometric picture of effective Cuscuton theory",
    caption: "The geometric picture of effective Cuscuton theory: a stack of non-identical spatial branes, adapted from the paper.",
    archiveHref: "/welcome/research/modified-gravity-and-the-cosmological-constant-problem/",
    papers: [
      { year: "2024", title: "A cosmic glitch in gravity", href: "https://arxiv.org/abs/2311.03028" },
      { year: "2024", title: "A glitch in gravity: cosmic Lorentz violation from fiery Big Bang to glacial heat death", href: "https://arxiv.org/abs/2412.09568" },
      { year: "2023", title: "Effective Cuscuton Theory", href: "https://arxiv.org/abs/2312.06066" },
    ],
  },
  {
    id: "dark-matter-structure",
    title: "Dark matter, galaxies & nonlinear structure",
    description: "I use cosmological simulations, analytic models, and interpretable machine learning to map dark objects and understand nonlinear structure, from dark-galaxy prediction to halo outskirts and phase space.",
    image: "/media/2016/01/p2sad_subs_only-eps-converted-to.jpg",
    alt: "Scientific phase-space plot for dark-matter halos of different masses",
    caption: "Phase-space structure across dark-matter haloes of different masses.",
    archiveHref: "/welcome/research/understanding-dark-matter-and-dark-energy/",
    papers: [
      { year: "2025", title: "Where are all the dark galaxies?", href: "https://arxiv.org/abs/2507.01814" },
      { year: "2022", title: "On the outskirts of dark matter haloes", href: "https://arxiv.org/abs/2210.11499" },
      { year: "2019", title: "Amending the halo model to satisfy cosmological conservation laws", href: "https://arxiv.org/abs/1912.04872" },
      { year: "2015", title: "Universal clustering of dark matter in phase space", href: "https://arxiv.org/abs/1508.02713" },
    ],
  },
  {
    id: "cosmic-gas-cmb",
    title: "Cosmic gas, the CMB & missing baryons",
    description: "I use the thermal and kinematic Sunyaev–Zel’dovich effects to trace hot electrons, galaxy motions, and the baryonic content of halos and intergalactic space while separating radio, dust, and infrared foregrounds.",
    image: "/media/2015/07/planck_cmb.jpg",
    alt: "All-sky map of fluctuations in the cosmic microwave background",
    caption: "The cosmic microwave background is both a primordial record and a backlight for cosmic gas.",
    archiveHref: "/welcome/research/missing-baryons-of-the-universe/",
    papers: [
      { year: "2026", title: "Thermal Sunyaev–Zel’dovich cross-correlations with unWISE galaxies", href: "https://arxiv.org/abs/2606.28099" },
      { year: "2013", title: "An optimal and model-independent measurement of the intracluster pressure profile", href: "https://arxiv.org/abs/1304.6457" },
      { year: "2012", title: "First measurement of the bulk flow of nearby galaxies using the CMB", href: "https://arxiv.org/abs/1207.1721" },
    ],
  },
  {
    id: "compact-objects",
    title: "Compact objects, accretion disks & electromagnetic probes",
    description: "I study observable signatures of black holes, neutron stars, white dwarfs, and modified strong gravity. Accretion spectra, self-lensing, and eclipses complement gravitational-wave tests.",
    image: "/media/2018/03/mass_spin.jpg",
    alt: "Scientific plot comparing inferred black-hole mass and spin",
    caption: "Mass and spin constraints illustrate the link between compact-object models and data.",
    archiveHref: "/welcome/research/understanding-accretion-disks/",
    papers: [
      { year: "2025", title: "Accretion disk dynamics in Teleparallel Born–Infeld gravity", href: "https://arxiv.org/abs/2502.03775" },
      { year: "2024", title: "Self-lensing and eclipsing signals from detached compact objects in TESS", href: "https://arxiv.org/abs/2409.12441" },
    ],
  },
  {
    id: "quantum-spacetime-foundations",
    title: "Quantum spacetime, analogue gravity & foundations",
    description: "I investigate operational and analogue probes of quantum spacetime, from detectors in superposed geometries to condensed-matter systems that reproduce black-hole thermodynamics, alongside surveys of unresolved foundational questions.",
    image: "/media/2025/05/image.png",
    alt: "Artist's impression of the energetic early universe",
    caption: "Foundational questions connect quantum spacetime, cosmology, and observable tests.",
    archiveHref: "/welcome/research/quantum-field-theory-in-curved-spacetime/",
    papers: [
      { year: "2024", title: "Accelerated detector in a superposed spacetime", href: "https://arxiv.org/abs/2409.06818" },
      { year: "2024", title: "Smart Holes: analogue black holes with the right temperature and entropy", href: "https://arxiv.org/abs/2412.08517" },
      { year: "2026", title: "Big Mysteries Survey", href: "https://arxiv.org/abs/2605.11058" },
      { year: "2025", title: "Copenhagen Survey on Black Holes and Fundamental Physics", href: "https://arxiv.org/abs/2503.15776" },
    ],
  },
  {
    id: "medical-physics",
    title: "Medical physics & radiotherapy",
    description: "I apply statistical and multiscale physics to radiation transport, microscopic energy deposition, and temperature profiles in tissue. This work helps clarify the mechanisms that shape FLASH ultra-high-dose-rate radiotherapy and other particle-therapy responses.",
    image: "/images/flash-radiotherapy-temperature-profile.png",
    alt: "Temperature increase as a function of distance from a therapeutic ion track for several particle energies",
    caption: "Temperature profiles around a therapeutic ion track, from work on FLASH radiotherapy.",
    archiveHref: "/publications",
    archiveLabel: "Related publications →",
    papers: [
      { year: "2025", title: "A semiclassical model of the immediate temperature distribution surrounding the track of heavy ions with therapeutic energies", href: "https://doi.org/10.1088/1361-6560/add83b" },
      { year: "2022", title: "The effect of non-ionizing excitations on the diffusion of ion species and inter-track correlations in FLASH ultra-high dose rate radiotherapy", href: "https://arxiv.org/abs/2201.07887" },
    ],
  },
  {
    id: "epidemiology",
    title: "Epidemiology & public-health modelling",
    description: "During the COVID-19 pandemic, I developed data-driven models of local epidemic growth that separated the effects of population density, demographics, climate, susceptible depletion, and interventions. The work connected transparent modelling to public dashboards and accessible public communication.",
    image: "/media/2020/07/us_county_lambda_map.jpeg",
    alt: "County-level United States map of predicted COVID-19 mortality growth rate",
    caption: "A county-level COVID-19 growth-rate projection from the preserved public-health modelling archive.",
    archiveHref: "/covid/",
    archiveLabel: "COVID-19 project archive →",
    papers: [
      { year: "2020", title: "Diverse local epidemics reveal the distinct effects of population density, demographics, climate, depletion of susceptibles, and intervention in the first wave of COVID-19 in the United States", href: "https://arxiv.org/abs/2007.00159" },
    ],
  },
];

export type GroupMember = {
  name: string;
  role: string;
  years: string;
  research: string;
  destination: string;
  image?: string;
  profileHref?: string;
  secondaryProfileHref?: string;
  secondaryProfileLabel?: string;
  verification?: string;
};

export const currentPeople: GroupMember[] = [
  {
    name: "Alice Chen",
    role: "PhD researcher",
    years: "2023–present",
    research: "Machine learning and cosmic structure formation, following earlier MSc work on cosmological structure.",
    destination: "University of Waterloo and Perimeter Institute.",
    image: "/images/alice-chen.webp",
    profileHref: "https://uwaterloo.ca/astrophysics-centre/contacts/alice-chen",
  },
  {
    name: "Ruolin Liu",
    role: "PhD student",
    years: "2023–present",
    research: "Quadratic gravity, the Big Bang, quantum black holes, and quantum sensors.",
    destination: "Perimeter Institute and University of Waterloo.",
    image: "/images/ruolin-liu.png",
    profileHref: "https://perimeterinstitute.ca/people/ruolin-liu",
  },
  {
    name: "Hassan Subhi",
    role: "MMath researcher",
    years: "2025–2027",
    research: "Gravitational-wave echoes in pulsar-timing data; co-supervised with Florian Girelli.",
    destination: "University of Waterloo.",
    image: "/images/hassan-subhi.png",
    profileHref: "https://www.linkedin.com/in/hassan-ihssan-subhi-23623a175/",
    secondaryProfileHref: "https://www.instagram.com/hassan.ihssan/",
    secondaryProfileLabel: "Instagram",
  },
  {
    name: "Shokoufe Faraji",
    role: "Postdoctoral researcher",
    years: "2024–2027",
    research: "Strong gravity, quantum gravity, and accretion around black holes.",
    destination: "Perimeter Institute and University of Waterloo.",
    image: "/images/shokoufe-faraji.png",
    profileHref: "https://perimeterinstitute.ca/people/shokoufe-faraji",
  },
  {
    name: "Ohoud K. Alharbi",
    role: "PhD student",
    years: "2026–2030",
    research: "PhD research in astrophysics and cosmology; topic to be confirmed.",
    destination: "University of Waterloo.",
    image: "/images/ohoud-alharbi.png",
    profileHref: "https://www.linkedin.com/in/ohoud-k-alharbi/",
    verification: "Please confirm the research topic and provide a preferred portrait.",
  },
  {
    name: "Harrison (Haoye) Li",
    role: "MSc student",
    years: "2026–2028",
    research: "MSc research in astrophysics and cosmology; topic to be confirmed.",
    destination: "University of Waterloo.",
    image: "/images/harrison-li.png",
    profileHref: "https://www.linkedin.com/in/haoye-li-60b22632a/",
    verification: "Please confirm the research topic and provide a preferred portrait.",
  },
  {
    name: "Robin Oberfrank",
    role: "PhD student",
    years: "Current",
    research: "PhD research in astrophysics and cosmology; co-supervised by Niayesh Afshordi.",
    destination: "Perimeter Institute and University of Waterloo.",
    image: "/images/robin-oberfrank.png",
    profileHref: "https://perimeterinstitute.ca/people/robin-oberfrank",
    verification: "Please confirm the research topic.",
    verification: "Please provide a preferred portrait and research title.",
  },
  {
    name: "Aliv Sahoo",
    role: "Undergraduate intern",
    years: "2026",
    research: "Undergraduate research internship; project details to be confirmed.",
    destination: "University of Waterloo.",
    image: "/images/aliv-sahoo.png",
    profileHref: "https://www.linkedin.com/in/aliv-sahoo-8b90b8346/",
    verification: "Please confirm the project description and provide a preferred portrait.",
  },
  {
    name: "Yusuke Manita",
    role: "Postdoctoral researcher",
    years: "2024–2026",
    research: "Cosmology and related observational probes of fundamental physics.",
    destination: "Perimeter Institute.",
    image: "/images/yusuke-manita.png",
    profileHref: "https://perimeterinstitute.ca/people/yusuke-manita",
  },
  {
    name: "Batia Friedman-Shaw",
    role: "PhD student (co-supervised)",
    years: "2023–present",
    research: "Cosmology, dark energy, vacuum decay, and galaxy-survey systematics.",
    destination: "Perimeter Institute and University of Waterloo.",
    image: "/images/batia-friedman-shaw.jpg",
    profileHref: "https://batia.me/",
  },
];

const cvAlumniAdditions: GroupMember[] = [
  { name: "Nabeel Rasheed", role: "Undergraduate researcher", years: "2023–2025", research: "Analytic gravitational-waveform templates.", destination: "PhD student, Massachusetts Institute of Technology." },
  { name: "Ruijing Tang", role: "BSc researcher", years: "2023–2025", research: "Teleparallel Born–Infeld gravity and accretion-disk dynamics.", destination: "Former group member." },
  { name: "Saral Shah", role: "Bachelor’s Honours researcher", years: "2024–2025", research: "Dynamical friction in a neutrino sea.", destination: "Former group member.", profileHref: "https://ca.linkedin.com/in/saral-shah" },
  { name: "Lyvia Yanover", role: "Bachelor’s Honours researcher", years: "2024–2025", research: "The bi-thermal Big Bang.", destination: "Former group member.", profileHref: "https://uwaterloo.ca/astrophysics-centre/contacts/lyvia-yanover" },
  { name: "Nikhil Murali", role: "Bachelor’s Honours researcher", years: "2024–2025", research: "Quantum corrections at the tip of a cigar.", destination: "Former group member." },
  { name: "Alex Dominic Raul Brisebois", role: "Bachelor’s Honours researcher", years: "2024–2025", research: "Clustering in action–angle space.", destination: "Former group member." },
  { name: "Arad Nasiri", role: "Doctoral researcher", years: "2023–2025", research: "Stochastic dark matter and covariant Brownian motion.", destination: "Former group member.", profileHref: "https://www.researchgate.net/profile/Arad-Nasiri" },
  { name: "Everett Avison Patterson", role: "Doctoral researcher", years: "2023–2024", research: "Accelerated detectors in superposed spacetimes.", destination: "Former group member.", profileHref: "https://uwaterloo.ca/astrophysics-centre/contacts/everett-patterson" },
  { name: "Johanna Borissova", role: "Doctoral researcher", years: "2022–2025", research: "Scale invariance at the core of quantum black holes.", destination: "Former group member.", profileHref: "https://pirsa.org/speaker/Johanna-Borissova" },
  { name: "Leo Kim", role: "Doctoral researcher", years: "2022–2024", research: "Dark sirens and particle astrophysics.", destination: "Former group member.", profileHref: "https://www.queensu.ca/physics/people-search/leo-kim" },
  { name: "David Dunsky", role: "Postdoctoral researcher", years: "2024", research: "Dark-matter disk accretion into black holes.", destination: "Former group member." },
  { name: "Akshay Ghalsasi", role: "Postdoctoral researcher", years: "2024", research: "Dark-matter disk accretion onto black holes.", destination: "Former group member." },
  { name: "Alex Krolewski", role: "Postdoctoral researcher", years: "2023–2024", research: "Doppler bias and large-scale structure.", destination: "Former group member." },
  { name: "Jerome Quintin", role: "Postdoctoral researcher", years: "2023–2025", research: "Quadratic gravity in cosmology and black holes.", destination: "Former group member." },
  { name: "Farbod Hassani", role: "Postdoctoral researcher", years: "2022–2024", research: "Dynamical friction with cosmic neutrinos.", destination: "Former group member.", profileHref: "https://www.mn.uio.no/astro/english/people/aca/hassanif/index.html" },
  { name: "Maria Mylova", role: "Postdoctoral researcher", years: "2021–2025", research: "The thermal Big Bang and effective Cuscuton theory.", destination: "Former group member." },
  { name: "Farnik Nikakhtar", role: "Postdoctoral researcher", years: "2020–2024", research: "Clustering in action–angle space.", destination: "Former group member." },
  { name: "Xitai (John) Yin", role: "Undergraduate researcher", years: "2023–2024", research: "Black holes in quantum gravity.", destination: "MSc student, University of Waterloo." },
  { name: "Shafika Olalekan Koiki", role: "Undergraduate researcher", years: "2021", research: "COVID forecasting and online dashboard development.", destination: "Former group member." },
  { name: "Kasia Wisniewski", role: "Undergraduate researcher", years: "2021", research: "Black-hole echoes from the failed supernova AT2017be.", destination: "Operations Technician, GHGSat Inc." },
  { name: "Guandi Zhao", role: "Visiting undergraduate researcher", years: "2023–2024", research: "Thermal Sunyaev–Zel’dovich contribution from low-mass galaxies in unWISE.", destination: "MSc student, ETH Zurich." },
  { name: "Lakshay Goel", role: "Undergraduate researcher", years: "2023–2024", research: "Accelerated detectors in a superposed spacetime.", destination: "Former group member." },
  { name: "Hazel Gifford", role: "Bachelor’s researcher", years: "2023–2024", research: "Cuscuton theory and cosmology.", destination: "MSc student, Brock University." },
  { name: "Aryanna Schiebelbein", role: "Bachelor’s researcher", years: "2022–2023", research: "Mystery noise in LIGO.", destination: "PhD student, University of Toronto." },
  { name: "Yu Li", role: "Bachelor’s researcher", years: "2022–2024", research: "Cosmological scalar fields and orbital networks of quantum sensors.", destination: "PhD student, California Institute of Technology." },
  { name: "Jensen Lawrence", role: "Bachelor’s researcher", years: "2021–2023", research: "Universal horizons in Einstein–Aether theory.", destination: "PhD student, Massachusetts Institute of Technology." },
  { name: "Robin Wen", role: "Bachelor’s researcher", years: "2020–2023", research: "A cosmic glitch in gravity.", destination: "PhD student, California Institute of Technology." },
  { name: "Meagan Stewart", role: "Bachelor’s researcher", years: "2020–2021", research: "Transient weak lensing from quasar light curves.", destination: "MSc student, Simon Fraser University." },
  { name: "Shafayat Shawqi", role: "Bachelor’s researcher", years: "2020–2022", research: "Sorkin–Johnston effective field theory.", destination: "PhD student, University of Alberta." },
  { name: "Petra Duff", role: "Undergraduate researcher", years: "2020", research: "Echoes from the abyss.", destination: "PhD student, University of Toronto." },
  { name: "Palka Minhas", role: "Bachelor’s researcher", years: "2019–2022", research: "Fast radio bursts.", destination: "MSc student, McGill University." },
  { name: "Luke Bovard", role: "Bachelor’s Honours researcher", years: "2010–2011", research: "Undergraduate research in astrophysics.", destination: "Postdoctoral researcher, Goethe University." },
  { name: "Matthias Mueller", role: "Undergraduate researcher", years: "2008–2009", research: "Undergraduate research in astrophysics.", destination: "Postdoctoral Fellow, University of Florence." },
  { name: "Oleksandra Hrytseniak", role: "Master’s researcher", years: "2022–2023", research: "Search for flattened non-Gaussianity.", destination: "PhD student, Perimeter Institute and University of Waterloo." },
  { name: "Wan Zen Chua", role: "Master’s researcher", years: "2019–2020", research: "Electromagnetic albedo of fuzzballs.", destination: "PhD student, Cornell University." },
  { name: "Qingwen Wang", role: "Master’s and PhD researcher", years: "2015–2020", research: "Fuzzball approach to black holes and black-hole echology.", destination: "Senior Quant, Deloitte." },
  { name: "Abhineet Agarwal", role: "Master’s researcher", years: "2010–2012", research: "Thermal tachyacoustic cosmology.", destination: "PhD student, Jamia Millia University." },
  { name: "Jiayue Yang", role: "Master’s researcher", years: "2022–2024", research: "Entropy of analogue black holes in tilted Dirac-cone materials.", destination: "PhD student, University of Waterloo." },
  { name: "Supranta Boruah", role: "Master’s researcher", years: "2017–2018", research: "Milky Way mass and clustering in Gaia action space.", destination: "Postdoctoral Fellow, University of Pennsylvania." },
  { name: "Hyungjin Kim", role: "Master’s researcher", years: "2016–2017", research: "Cuscuton theory, modified dispersion relations, and pulsar constraints on vacuum noise.", destination: "PhD student, University of Waterloo." },
  { name: "Yosdanis Ponce", role: "Master’s researcher", years: "2009–2012", research: "Black-hole halo model and holographic cosmology.", destination: "Adjunct Faculty, Miami Dade College." },
  { name: "Valentin Boyanov Savov", role: "Visiting PhD researcher", years: "2022", research: "Aspects of quantum black holes in semiclassical gravity.", destination: "Postdoctoral Fellow, Instituto Superior Técnico, Lisbon." },
  { name: "Luis Felipe Longo", role: "Visiting PhD researcher", years: "2019–2024", research: "Echo diversity in binary-black-hole mergers and spectrogram correlated stacking.", destination: "European Research Council Postdoctoral Fellow, Friedrich Schiller University Jena." },
  { name: "Daichi Tsuna", role: "Visiting PhD researcher", years: "2019–2020", research: "Quantum black-hole seismology.", destination: "Sherman Fairchild Postdoctoral Scholar, California Institute of Technology." },
  { name: "Aaron Held", role: "Visiting PhD researcher", years: "2018–2019", research: "Quantum black holes in asymptotic safety.", destination: "Postdoctoral Fellow, École Normale Supérieure, Paris." },
  { name: "Utkarsh Giri", role: "Visiting PhD researcher", years: "2018–2019", research: "Pressure of haloes in cosmological simulations.", destination: "Postdoctoral Fellow, California Institute of Technology." },
  { name: "Elliott Nelson", role: "Postdoctoral researcher", years: "2014–2018", research: "Cosmological non-constant problem and quantum decoherence during inflation.", destination: "Research Scientist, IBM Research." },
  { name: "Ali Narimani", role: "Visiting PhD researcher", years: "2013–2014", research: "How does pressure gravitate?", destination: "Data Scientist, Twitter." },
  { name: "Jeremy Sakstein", role: "Visiting PhD researcher", years: "2013–2014", research: "Novel approaches to modified gravity.", destination: "Postdoctoral Fellow, University of Pennsylvania." },
  { name: "Sean Gryb", role: "PhD researcher", years: "2010–2011", research: "Shape dynamics and Mach’s principles.", destination: "Research Associate, University of Bristol." },
  { name: "Marilena LoVerde", role: "Visiting PhD researcher", years: "2007–2008", research: "Extended Limber approximation.", destination: "Assistant Professor, Stony Brook University." },
  { name: "Ramit Dey", role: "Postdoctoral researcher", years: "2020–2024", research: "Spectrogram correlated stacking and black-hole echoes.", destination: "Research Associate, Western University." },
  { name: "Barak Shoshani", role: "Postdoctoral researcher", years: "2020", research: "Bayesian search for black-hole echoes.", destination: "Assistant Professor, Brock University." },
  { name: "Takeshi Kobayashi", role: "Postdoctoral researcher", years: "2012–2015", research: "Primordial magnetic fields from the post-inflationary universe.", destination: "Postdoctoral Fellow, ICTP." },
];

export const alumniPeople: GroupMember[] = [
  {
    name: "Conner Dailey",
    role: "PhD researcher",
    years: "2020–2025",
    research: "The initial-boundary-value problem in numerical relativity and the modelling of black-hole echoes.",
    destination: "Postdoctoral researcher, Friedrich Schiller University Jena.",
    image: "/media/2024/09/conner-dailey-web.jpg",
    profileHref: "https://taketwicedailey.com/",
  },
  {
    name: "Matthew Robbins",
    role: "PhD researcher",
    years: "2017–2021",
    research: "Gravitational waves, Bose–Einstein-condensate detectors, modified gravity, and black holes.",
    destination: "Assistant Professor, Teaching Stream, University of Toronto.",
    image: "/media/2018/07/image-2.jpg",
    profileHref: "https://www.physics.utoronto.ca/members/robbins-matthew/",
  },
  {
    name: "José Tomás Gálvez Ghersi",
    role: "Visiting PhD researcher",
    years: "2017–2018",
    research: "Local-observer temperature in curved spacetime and modified gravity.",
    destination: "Associate Professor, Universidad de Ingeniería y Tecnología, Peru.",
    image: "/images/jose-tomas-ghersi.png",
    profileHref: "https://cris.utec.edu.pe/es/persons/jos%C3%A9-tom%C3%A1s-g%C3%A1lvez-ghersi/",
  },
  {
    name: "Mohammad Hossein Zhoolideh Haghighi",
    role: "Visiting PhD researcher",
    years: "2016–2017",
    research: "X-ray cooling flows, turbulent heating, and modified gravity.",
    destination: "Assistant Professor, K. N. Toosi University of Technology.",
    image: "/images/mohammad-haghighi.png",
    profileHref: "https://www.linkedin.com/in/mohammad-h-zhoolideh-9b041077/",
  },
  {
    name: "Chanda Prescod-Weinstein",
    role: "Co-supervised PhD researcher",
    years: "2008–2010",
    research: "Cosmic acceleration, quantum gravity, and early-universe cosmology.",
    destination: "Associate Professor, University of New Hampshire.",
    image: "/media/2015/07/chandacake_resized1-e1439880392164.jpg",
    profileHref: "https://cola.unh.edu/person/chanda-prescod-weinstein",
  },
  {
    name: "Daniel Guariento",
    role: "Postdoctoral researcher",
    years: "2013–2017",
    research: "Cosmological black holes, self-gravitating fields, and cosmic censorship.",
    destination: "Professor, Conestoga College.",
    image: "/media/2015/07/s200_daniel-guariento.jpg",
    profileHref: "https://www.researchgate.net/profile/Daniel-Guariento",
  },
  {
    name: "Michael Meiers",
    role: "Master’s researcher",
    years: "2014–2016",
    research: "Universal horizons and Lorentz-violating black holes.",
    destination: "Walmart Global Tech.",
    image: "/media/2015/07/michael-meiers-e1440388294268.jpg",
    profileHref: "https://www.linkedin.com/in/michael-meiers",
  },
  {
    name: "Samantha Hergott",
    role: "Master’s researcher",
    years: "2018–2020",
    research: "Thermal links between the Big Bang and black holes.",
    destination: "Recent York University and Perimeter Institute PhD graduate and black-hole researcher.",
    image: "/media/2019/05/unnamed-1.jpg",
    profileHref: "https://orcid.org/0000-0002-3954-3235",
    verification: "Please confirm current appointment.",
  },
  {
    name: "Aditya Dhumuntarao",
    role: "Visiting PhD researcher",
    years: "2017–2018",
    research: "Local temperature and quantum field theory in curved spacetime.",
    destination: "Postdoctoral Appointee, Sandia National Laboratories.",
    image: "/media/2018/04/aditya-e1522979303913.jpg",
    profileHref: "https://www.sandia.gov/people/staff/aditya-dhumuntarao/",
  },
  {
    name: "Naritaka Oshita",
    role: "Visiting PhD and postdoctoral researcher",
    years: "2018–2021",
    research: "Black-hole echoes and quantum black-hole seismology.",
    destination: "Lecturer, Kindai University; visiting researcher, RIKEN.",
    image: "/media/2019/05/picture-41146-1550674152.jpg",
    profileHref: "https://research.kindai.ac.jp/search/detail.html?lang=en&st=researcher&systemId=7142158ed6512951",
  },
  {
    name: "Mehdi Saravani",
    role: "PhD researcher",
    years: "2011–2016",
    research: "Nonlocality, causal sets, quantum field theory, and black holes.",
    destination: "Goldman Sachs, United Kingdom.",
    image: "/media/2015/07/11083918_10205089110560914_8792186586980474424_o-e1439884225953.jpg",
    profileHref: "https://uk.linkedin.com/in/mehdi-saravani",
    verification: "Please confirm current title.",
  },
  {
    name: "Hannah Dykaar",
    role: "Undergraduate researcher",
    years: "2016",
    research: "Gravitational-wave echoes from the abyss.",
    destination: "Postdoctoral Fellow, McGill University.",
    image: "/images/hannah-dykaar.png",
    profileHref: "https://www.dhaggard.physics.mcgill.ca/research-group",
  },
  {
    name: "Tianyi Yang",
    role: "Master’s researcher",
    years: "2018–2020",
    research: "Cosmic filaments, Gaia kinematics, and thermal Sunyaev–Zel’dovich gas.",
    destination: "Postdoctoral researcher, Liverpool John Moores University.",
    image: "/media/2018/04/photo-1-e1522977249934.png",
    profileHref: "https://uwaterloo.ca/scholar/mjhudson/group-members",
  },
  {
    name: "Mansour Karami",
    role: "PhD researcher",
    years: "2014–2018",
    research: "Dark matter, microlensing, halo modelling, and Event Horizon Telescope methods.",
    destination: "AI engineering, HOOPP.",
    image: "/media/2015/07/mypic-e1440388587637.jpg",
    profileHref: "https://ca.linkedin.com/in/mansour-karami",
    verification: "Please confirm current title.",
  },
  {
    name: "Razieh Pourhasan",
    role: "PhD researcher",
    years: "2011–2014",
    research: "Holography, the Big Bang, and spacetime entanglement.",
    destination: "Data Scientist, Government of Canada.",
    image: "/media/2015/07/msc-razieh-pourhasan-0001-20140805-158x185-e1439883375483.jpg",
    profileHref: "https://www.robbmanngroup.ca/people",
  },
  {
    name: "Chiamaka Okoli",
    role: "Master’s and PhD researcher",
    years: "2012–2018",
    research: "Dark matter, halo concentration, and cosmological neutrino wakes.",
    destination: "In memoriam (died June 2019).",
    image: "/media/2015/07/26d8193-e1440385821548.jpg",
    profileHref: "https://perimeterinstitute.ca/news/perimeter-mourns-passing-chiamaka-okoli-brilliant-rising-star-cosmology",
  },
  {
    name: "Jesús Zavala",
    role: "Postdoctoral researcher",
    years: "2010–2013",
    research: "Dark-matter phase space, structure, and galaxy formation.",
    destination: "Professor, University of Iceland.",
    image: "/media/2015/07/jesus.jpg",
    profileHref: "https://hi.is/staff/jzavala",
  },
  {
    name: "Elizabeth “Beth” Gould",
    role: "PhD researcher",
    years: "2011–2017",
    research: "Early-universe cosmology, quantum foundations, and holographic cosmology.",
    destination: "Former group member.",
    image: "/images/elizabeth-beth-gould.png",
  },
  {
    name: "Yasaman K. Yazdi",
    role: "Master’s and PhD researcher",
    years: "2011–2017",
    research: "Vacuum states, entropy, black holes, and causal sets.",
    destination: "Postdoctoral Fellow, Dublin Institute for Advanced Studies.",
    image: "/media/2015/07/img_1650_2-e1440387894698.jpg",
    profileHref: "https://royalsociety.org/science-events-and-lectures/2026/09/path-to-quantum-gravity/",
  },
  {
    name: "Morag Scrimgeour",
    role: "Postdoctoral researcher",
    years: "2013–2014",
    research: "Large-scale structure and cosmological neutrinos.",
    destination: "Scientist, Canon Medical Research Europe.",
    image: "/media/2015/07/morag-e1439882456847.jpg",
    profileHref: "https://uwaterloo.ca/scholar/mjhudson/group-members",
  },
  {
    name: "Guilhem Lavaux",
    role: "CITA National Fellow",
    years: "2011–2013",
    research: "Missing baryons, cosmic flows, and large-scale structure.",
    destination: "CNRS Research Director, Institut d’Astrophysique de Paris.",
    image: "/media/2015/07/me-e1439881349111.jpg",
    profileHref: "https://www.guilhem-lavaux.eu/cv.php",
  },
  {
    name: "Zachary Elgood",
    role: "Undergraduate researcher",
    years: "2016",
    research: "Einstein–Aether black holes.",
    destination: "Former undergraduate researcher.",
    image: "/media/2018/04/23736341_10208680484004424_6004154379800524268_o-e1522976735527.jpg",
    profileHref: "https://www.linkedin.com/in/zachary-elgood-aba33620/",
  },
  {
    name: "Connor Adair",
    role: "Undergraduate researcher",
    years: "2017",
    research: "Gravitational-wave echoes.",
    destination: "Candu Energy Inc.",
    image: "/media/2019/02/profile-pic.jpg",
    profileHref: "https://ca.linkedin.com/in/connor-adair-614b24177",
  },
  {
    name: "Natacha Altamirano",
    role: "PhD researcher",
    years: "2014–2018",
    research: "Quantum gravity, black holes, and holographic cosmology.",
    destination: "Senior Director, Data Science, Birch Hill Equity Partners.",
    image: "/media/2018/07/img_3950-e1531213584786.jpg",
    profileHref: "https://perimeterinstitute.ca/training/alumni-network/perimeter-circle-alumni-stories/natacha-altamirano-bringing-data-driven",
  },
  {
    name: "Nosiphiwo Zwane",
    role: "PhD researcher",
    years: "2013–2017",
    research: "Causal-set phenomenology, dark energy, and Everpresent Lambda.",
    destination: "Lecturer and researcher, University of Eswatini.",
    image: "/media/2015/07/aims_nosiphiwo_zwane-e1440389254459.jpg",
    profileHref: "https://www.linkedin.com/in/nosiphiwo-zwane-414878276/",
  },
  {
    name: "Eleanna Kolonia",
    role: "Research Assistant",
    years: "Former",
    research: "Research assistance in astrophysics and cosmology.",
    destination: "PhD student, Swansea University.",
    image: "/images/eleanna-kolonia.png",
    profileHref: "https://www.linkedin.com/in/eleni-anna-kolonia-229263247/",
  },
  {
    name: "Shant Baghram",
    role: "Postdoctoral researcher",
    years: "2011–2012",
    research: "Dark-matter halo substructure, pulsar timing, and modified gravity.",
    destination: "Professor, Sharif University of Technology.",
    image: "/media/2015/07/photo.jpg",
    profileHref: "https://www.iau.org/IAU/Shared_Content/Contacts/ContactLayouts/Profile.aspx?ID=38854",
  },
  {
    name: "Farbod Kamiab",
    role: "PhD researcher",
    years: "2011–2015",
    research: "Neutron stars, modified gravity, and numerical relativity.",
    destination: "Director of AI and Data Engineering, Everlywell.",
    image: "/media/2015/07/shapeimage_6-e1439883765262.png",
    profileHref: "https://www.linkedin.com/in/farbod-kamiab-78461135",
  },
  {
    name: "Jahed Abedi",
    role: "Visiting and co-supervised PhD researcher",
    years: "2016–2018",
    research: "Black-hole echoes and gravitational-wave data.",
    destination: "Assistant Professor, Beijing Institute of Mathematical Sciences and Applications.",
    image: "/media/2015/07/photo1.jpg",
    profileHref: "https://www.bimsa.cn/detail/JahedAbedi.html",
  },
  {
    name: "Siavash Aslanbeigi",
    role: "PhD researcher",
    years: "2010–2014",
    research: "Causal sets, nonlocality, and cosmological structure.",
    destination: "BMO Capital Markets.",
    image: "/media/2015/07/29cfc18.jpg",
    profileHref: "https://ca.linkedin.com/in/siavash-aslanbeigi-b8232745",
    verification: "Please confirm current title.",
  },
  {
    name: "Krishan Saraswat",
    role: "PhD researcher",
    years: "2018–2023",
    research: "Black-hole microstates, echoes, quantum chaos, and holography.",
    destination: "Postdoctoral Researcher, University of California, Santa Barbara.",
    image: "/media/2019/02/0.jpeg",
    profileHref: "https://orcid.org/0000-0002-0350-7822",
  },
  {
    name: "Morgan Lynch",
    role: "Visiting PhD researcher",
    years: "2015–2016",
    research: "Curved-spacetime quantum field theory and the Unruh effect.",
    destination: "Postdoctoral researcher, Max Planck Institute for Nuclear Physics.",
    image: "/media/2015/07/lynch_300-e1440391901651.jpg",
  },
  {
    name: "Jolene Zheng",
    role: "Undergraduate researcher",
    years: "2021",
    research: "COVID forecasting and dashboard development.",
    destination: "Software Engineer, Bloomberg.",
    image: "/media/2021/04/image-14.png",
    profileHref: "https://www.linkedin.com/in/jolenezheng/",
  },
  ...cvAlumniAdditions,
];

export const currentMembers = currentPeople.map((member) => member.name);

export const recentTalks = [
  {
    date: "May 31–June 5, 2026",
    title: "Quantum Gravity in the Wild: Testing Horizon-Scale Physics with Gravitational Waves and Cosmology",
    venue: "Recent Development of Quantum Gravity and Applications to Cosmology and Black Hole Physics · Hangzhou, China",
    href: "/talks/quantum-gravity-in-the-wild-hangzhou-2026.pdf",
  },
  {
    date: "April 16, 2025",
    title: "Copenhagen Survey on Black Holes and Fundamental Physics",
    venue: "IPM Physics Colloquium · Institute for Research in Fundamental Sciences",
    href: "/talks/copenhagen-survey-black-holes-ipm-2025.pdf",
  },
  {
    date: "July 24, 2024",
    title: "Imaging Quantum Black Holes & (Towards) Optimal Estimators of Stochastic Gravitational Wave Background",
    venue: "The 1st Tsinghua Relativity Workshop",
    href: "/talks/imaging-quantum-black-holes-tsinghua-2024.pdf",
  },
  {
    date: "January 29–March 1, 2024",
    title: "Precision Quantum Cosmology: Past, Present, and Future",
    venue: "Gravity and Cosmology 2024 · Yukawa Institute for Theoretical Physics, Kyoto University",
    href: "/talks/precision-quantum-cosmology-kyoto-2024.pdf",
  },
];

export const talksArchiveUrl = "/talks/#historical-talks";

export const recentUpdates = [
  {
    date: "March 2025",
    title: "Join Me at the Royal Institution — Battle of the Big Bang",
    href: "/2025/03/25/join-me-at-the-royal-institution-on-june-28-battle-of-the-big-bang/",
  },
  {
    date: "January 2025",
    title: "Meaning of Beauty :معنی قشنگ",
    href: "/2025/01/20/meaning-of-beauty-%d9%85%d8%b9%d9%86%db%8c-%d9%82%d8%b4%d9%86%da%af/",
  },
  {
    date: "October 2024",
    title: "Battle of the Big Bang: New Tales of Our Cosmic Origins",
    href: "/2024/10/19/battle-of-the-big-bang-new-tales-of-our-cosmic-origins/",
  },
];

export const battleOfBigBang = {
  title: "Battle of the Big Bang",
  subtitle: "The New Tales of Our Cosmic Origins",
  authors: "Niayesh Afshordi and Phil Halper",
  cover: "/media/2024/12/9780226830476.jpg",
  description: "A guided tour through competing ideas about cosmic origins—from bouncing and cyclic universes to black-hole births, multiverses, holograms, and the possibility that the Big Bang was not the beginning.",
  links: [
    { label: "University of Chicago Press", href: "https://press.uchicago.edu/ucp/books/book/chicago/B/bo244963115.html" },
    { label: "Amazon.com", href: "https://www.amazon.com/dp/0226830470" },
    { label: "Amazon.ca", href: "https://www.amazon.ca/dp/0226830470" },
    { label: "Audiobook details", href: "https://rbmediaglobal.com/audiobook/9798318515187/" },
  ],
  reviews: [
    { label: "The Wall Street Journal review — A Question of Origins", href: "https://www.wsj.com/public/resources/documents/e3nmpymJpO50ZWvNOXUk-WSJNewsPaper-8-7-2025.pdf" },
    { label: "The Wall Street Journal — Five Best: Cosmic Origins and Endings (publisher excerpt)", href: "https://press.uchicago.edu/ucp/books/book/chicago/B/bo244963115.html" },
    { label: "Smithsonian Magazine — Ten Best Science Books of 2025", href: "https://www.smithsonianmag.com/science-nature/the-ten-best-science-books-of-2025-180987773/" },
    { label: "Times Literary Supplement", href: "https://www.the-tls.com/science-technology/sciences/battle-of-the-big-bang-niayesh-afshordi-phil-halper-review-philip-ball" },
    { label: "Physics World", href: "https://physicsworld.com/a/beyond-the-big-bang-reopening-the-doors-on-how-it-all-began/" },
    { label: "Publishers Weekly", href: "https://www.publishersweekly.com/9780226830476" },
    { label: "Literary Review of Canada", href: "https://reviewcanada.ca/magazine/2025/10/in-the-beginning-review-battle-of-the-big-bang/" },
    { label: "Newcity", href: "https://lit.newcity.com/2025/06/02/who-really-knows-a-review-of-battle-of-the-big-bang-by-niayesh-afshordi-and-phil-halper/" },
    { label: "Library Journal", href: "https://www.libraryjournal.com/review/battle-of-the-big-bang-the-new-tales-of-our-cosmic-origins-1815275" },
    { label: "Popular Science Books", href: "https://popsciencebooks.blogspot.com/2025/06/battle-of-big-bang-niayesh-afshordi-and.html" },
  ],
  interviews: [
    { date: "June 2025", title: "What Really Happened During the Big Bang? — Royal Institution", href: "https://youtu.be/Tx0net82eTo" },
    { date: "August 2025", title: "What Came Before the Big Bang? — Alex O'Connor interview", href: "https://youtu.be/rscDW-l8N0Q" },
    { date: "June 2025", title: "Public Lecture Livestream — Perimeter Institute", href: "https://www.youtube.com/watch?v=ns4OHQjHreE&t=1s" },
    { date: "April 2026", title: "The Big Bang May Not Be the Beginning: Time and Nothingness", href: "https://youtu.be/qj5wCEfpqc0" },
    { date: "May 2026", title: "What Came Before The Big Bang?", href: "https://youtu.be/lFVqEZ1qF_g" },
    { date: "October 2025", title: "Has Science Just Proved God?", href: "https://youtu.be/DO5iArbukzg" },
    { date: "September 2025", title: "Are We Wrong About the Big Bang?", href: "https://youtu.be/2j0Mv74VjTI" },
    { date: "June 2025", title: "Was There Anything Before Us?", href: "https://youtu.be/xuMAoME_FvE" },
    { date: "May 2025", title: "Mindscape: The Big Bang and Before", href: "https://youtu.be/iG1IYItjgeA" },
    { date: "May 2025", title: "نبرد مهبانگ: روایتهای نو از خاستگاه کیهانی ما", href: "https://youtu.be/cZzxoYCEf2Y" },
    { date: "January 2025", title: "Peppering a Cosmologist with All My Questions", href: "https://youtu.be/N8him6_yH3E" },
  ],
};

export const externalProfiles = [
  { label: "arXiv", href: "https://arxiv.org/search/?searchtype=author&query=Afshordi%2C+N&order=-announced_date_first&size=200&abstracts=show" },
  { label: "INSPIRE", href: "https://inspirehep.net/authors/1023532" },
  { label: "NASA ADS", href: "https://ui.adsabs.harvard.edu/search/q=author%3A%22Afshordi%22" },
  { label: "Google Scholar", href: "https://scholar.google.ca/citations?user=xWZGFlEAAAAJ&hl=en" },
  { label: "ORCID", href: "https://orcid.org/0000-0002-9940-7040" },
  { label: "Mathematics Genealogy", href: "https://www.mathgenealogy.org/id.php?id=84888" },
];

export const recentMediaCoverage = [
  {
    year: "2026",
    title: "New theory reshapes quantum view of Big Bang",
    detail: "Perimeter Institute and University of Waterloo news, March 2026",
    href: "https://perimeterinstitute.ca/news/new-theory-reshapes-quantum-view-big-bang",
    image: "/media/2026/02/image.png",
  },
  {
    year: "2026",
    title: "The Big Bang May Not Be the Beginning: Dr. Niayesh Afshordi on Time and Nothingness",
    detail: "Philosophy Everyday interview, April 2026",
    href: "https://youtu.be/qj5wCEfpqc0",
    youtubeId: "qj5wCEfpqc0",
  },
  {
    year: "2026",
    title: "What Came Before The Big Bang?",
    detail: "Apple Finch Pudding interview, May 2026",
    href: "https://youtu.be/lFVqEZ1qF_g",
    youtubeId: "lFVqEZ1qF_g",
  },
  {
    year: "2025",
    title: "Has Science Just Proved God?",
    detail: "Premier Unbelievable? debate with Michel-Yves Bollore, October 2025",
    href: "https://youtu.be/DO5iArbukzg",
    youtubeId: "DO5iArbukzg",
  },
  {
    year: "2025",
    title: "In the Beginning",
    detail: "Literary Review of Canada review by Dan Falk, October 2025",
    href: "https://reviewcanada.ca/magazine/2025/10/in-the-beginning-review-battle-of-the-big-bang/",
    image: "/media/2025/05/image.png",
  },
  {
    year: "2025",
    title: "Are We Wrong About the Big Bang?",
    detail: "Dr Brian Keating interview, September 2025",
    href: "https://youtu.be/2j0Mv74VjTI",
    youtubeId: "2j0Mv74VjTI",
  },
  {
    year: "2025",
    title: "Was There Anything Before Us?",
    detail: "Event Horizon interview with Phil Halper, June 2025",
    href: "https://youtu.be/xuMAoME_FvE",
    youtubeId: "xuMAoME_FvE",
  },
  {
    year: "2025",
    title: "Who Really Knows? A Review of Battle of the Big Bang",
    detail: "Newcity review by Patrick Roberts, June 2025",
    href: "https://lit.newcity.com/2025/06/02/who-really-knows-a-review-of-battle-of-the-big-bang-by-niayesh-afshordi-and-phil-halper/",
    image: "/media/2025/05/image-1.png",
  },
  {
    year: "2025",
    title: "Mindscape 316: Niayesh Afshordi and Phil Halper on the Big Bang and Before",
    detail: "Sean Carroll's Mindscape interview, May 2025",
    href: "https://youtu.be/iG1IYItjgeA",
    youtubeId: "iG1IYItjgeA",
  },
  {
    year: "2025",
    title: "Battle of the Big Bang: The New Tales of Our Cosmic Origins",
    detail: "Library Journal review, April 2025",
    href: "https://www.libraryjournal.com/review/battle-of-the-big-bang-the-new-tales-of-our-cosmic-origins-1815275",
    image: "/media/2024/12/9780226830476.jpg",
  },
] as const;

export const socialProfiles = [
  { label: "LinkedIn", href: "https://www.linkedin.com/in/niayesh-afshordi-61739462/" },
  { label: "X", href: "https://x.com/nafshordi" },
  { label: "Bluesky", href: "https://bsky.app/profile/nafshordi.bsky.social" },
  { label: "Facebook", href: "https://www.facebook.com/niayesh.afshordi" },
  { label: "Threads", href: "https://www.threads.net/@nafshordi" },
  { label: "Instagram", href: "https://www.instagram.com/nafshordi/" },
] as const;
